language: node_js
branches:
  only:
  - master
before_script: bash ./bin/prepare.sh
script:
  - ls -al wapuu.json
after_success: bash ./bin/deploy.sh
env:
  global:
  - GH_REF: github.com/jawordpressorg/wapuu-api.git
  - secure: xxxx
