language: node_js
branches:
  only:
  - master
before_script: bash ./bin/prepare.sh
script:
  - ls -al wapuu.json
after_success: bash ./bin/deploy.sh
env:
  global:
  - GH_REF: github.com/jawordpressorg/wapuu-api.git
  - secure: "uENgMzrxYjhCjFNoq3QeuJd8K2IN4Q4JAYbhJ7I8UOx+wVfiKdXN+Xn8PXSePPCaqvBqxR2g4jeLy0M1wy7fhxEdtcNiXQelUvE+rbLnzc+2+xDjwtuO7NHbFjbx2L2OZWxQ/NCrLSFMZypNMSjCKivVExNqKqdFVMZ4efRoEltzHjJy0RIr777LyXsjXIgkfXAlIiHWAKJl26QtgYymRAYauEnCmacknhEYbnLNpY9N/oUoRfgjp/ii7SnpijRCop7IrmBOMyMUrPnNFTynknrm7Dbz7FORcaWpQsUH+VpZqpOMilnaOiPB+AyxV9inGl1/uBJPdGDQkCKH3cPwaPsZwFc7wHdXf9dmGMCrq5MCWMxpcBArZBMfkATP+UPyDGkAn3XIzZZrqRtiuKKtbl5GpAeLQ6atmsi9gFMrkmZgyz+5JeCNWiSKECyjHXdrgcXpLa+e2xFbEXULBQtU+9UfnfacHVxGb5nc+h+lR0mwc42OQFKLSpbo2P/PMnBC1kC449wJo9s7NLJX3hLJgk6QQjZ3WNcvG8HB5KRHQFP526TCk2r5GxLg0u6rPEtq1hzcMMTrEw1ZuJ33pe4iVjIeo/UXkaq6t5he4VR8F2PaRdJ7bUFH6qJEf2IDVeRe0O9ZELdc1+ZB19n81oqunbQ3rYhWC7kaDdCNrXrEdyE="
